name: Go package

on:
  push:
    tags:
      - "v*" # push events to tagged commits
    branches:
      - "**"
permissions:
  contents: read
  id-token: write # for GitHub id-token auth

jobs:
  push-docker:
    if: startsWith(github.ref, 'refs/tags/v') # only run this step on tagged commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Build and push Docker images and manifests
        working-directory: src
        run: make push-images ${{ startsWith(github.ref, 'refs/tags/v') && format('VERSION={0}', github.ref_name) || '' }}

  on-failure:
    runs-on: ubuntu-latest
    if: failure() && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    needs: [push-docker]
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_TITLE: OpenAI Access Gateway workflow failed
        MSG_MINIMAL: actions url
        SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFIER_WEBHOOK_URL }}
